# Generated by Django 6.1.1 on 2026-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_reserve_rate', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metric', models.CharField(choices=[('revenue', 'Umsatz'), ('profit', 'Gewinn')], default='revenue', max_length=16)),
                ('period', models.CharField(choices=[('monthly', 'Monatlich'), ('yearly', 'Jährlich'), ('total', 'Gesamt')], default='yearly', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
