# Generated by Django 6.1.1 on 2026-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='ebay_fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
