# Generated by Django 6.1.1 on 2026-09-26 14:15

import django.db.models.deletion
import products_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products_app.models.product_image_path)),
                ('position', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products_app.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
