# Generated by Django 6.1.1 on 2026-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_product_status_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('reserved', 'Reserviert'), ('sold', 'Verkauft'), ('archived', 'Archiviert')], default='available', max_length=16),
        ),
    ]
