# Generated by Django 6.1.1 on 2026-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('reserved', 'Reserviert'), ('sold', 'Verkauft'), ('archived', 'Archiviert')], db_index=True, default='available', max_length=16),
        ),
    ]
