# Generated by Django 6.1.1 on 2026-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ebay_username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='reklamation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('open', 'Offen'), ('packed', 'Verpackt'), ('shipped', 'Verschickt'), ('delivered', 'Zugestellt'), ('in_return', 'In Reklamation'), ('cancelled', 'Storniert')], default='open', max_length=16),
        ),
    ]
