# Generated by Django 6.1.1 on 2026-09-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_buyer_name_order_ebay_username_and_more'),
        ('products_app', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products_app.product'),
        ),
    ]
