# Generated by Django 6.1.1 on 2026-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_rename_reklamation_note_order_return_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sold_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
