# Generated by Django 6.1.1 on 2026-10-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_alter_order_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ebay_order_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ebay_line_item_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manuell'), ('ebay', 'eBay')], default='manual', max_length=8)),
                ('item_action', models.CharField(choices=[('available', 'Wieder verfügbar'), ('archive', 'Ins Archiv'), ('delete', 'Artikel gelöscht')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='orders_app.order')),
            ],
        ),
    ]
