# Generated by Django 6.1.1 on 2026-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_ebay_fields_and_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Bezahlt'), ('pending', 'Zahlung offen')], default='paid', max_length=8),
        ),
    ]
