# Generated by Django 6.1.1 on 2026-09-27 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('oauth_state', models.CharField(blank=True, max_length=64)),
                ('oauth_state_created_at', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_policy_id', models.CharField(blank=True, max_length=32)),
                ('return_policy_id', models.CharField(blank=True, max_length=32)),
                ('payment_policy_id', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EbayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_location_key', models.CharField(max_length=36, unique=True)),
                ('last_synced', models.DateTimeField()),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_location', to='logistics_app.warehouse')),
            ],
        ),
    ]
