# Generated by Django 6.1.1 on 2026-10-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0001_initial'),
        ('products_app', '0005_alter_product_purchase_date_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayaccount',
            name='orders_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EbayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps_url', models.URLField(max_length=500)),
                ('source_name', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_image', to='products_app.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=16)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('offer_id', models.CharField(blank=True, max_length=32)),
                ('listing_id', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('online', 'Online'), ('ended', 'Beendet')], default='draft', max_length=8)),
                ('synced_quantity', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_listing', to='products_app.product')),
            ],
        ),
    ]
