# Generated by Django 6.1.1 on 2026-10-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0002_listings_and_images'),
        ('products_app', '0005_alter_product_purchase_date_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_category_id', models.CharField(max_length=16)),
                ('ebay_category_name', models.CharField(blank=True, max_length=255)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_mapping', to='products_app.category')),
            ],
        ),
    ]
