# Generated by Django 6.1.1 on 2026-10-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0003_category_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('shipping_service', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('handling_days', models.PositiveSmallIntegerField(default=1)),
                ('policy_id', models.CharField(blank=True, max_length=32)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='best_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='ebay_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='facts_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='shipping_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='ebay_app.ebayshippingprofile'),
        ),
    ]
