# Generated by Django 6.1.1 on 2026-10-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0005_adopt_shipping_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayaccount',
            name='fulfillment_policy_id',
        ),
    ]
