# Generated by Django 6.1.1 on 2026-10-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0006_drop_account_fulfillment_policy'),
        ('products_app', '0006_sku_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='needs_migration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebaylisting',
            name='category_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='ebaylisting',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_listing', to='products_app.product'),
        ),
        migrations.AddConstraint(
            model_name='ebaylisting',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), ('needs_migration', False)), fields=('sku',), name='unique_ebay_listing_sku'),
        ),
    ]
